# Nama workflow yang akan muncul di tab "Actions" GitHub
name: 'Run Twitter AI Search'

# Pemicu (trigger) kapan workflow ini dijalankan
on:
  # 1. Menjalankan setiap jam
  schedule:
    - cron: '0 * * * *'
  # 2. Memungkinkan Anda menjalankan manual dari tab "Actions"
  workflow_dispatch:

# Daftar pekerjaan (jobs) yang akan dieksekusi
jobs:
  # Nama job (bisa apa saja)
  run_api_call:
    # Menentukan jenis mesin virtual untuk menjalankan job
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dijalankan
    steps:
      # Nama langkah (deskriptif)
      - name: 'Execute Gopher AI Search API'
        # Perintah yang akan dijalankan di terminal mesin virtual
        run: |
          curl https://data.gopher-ai.com/api/v1/search/live \
            -H "Authorization: Bearer ${{ secrets.GOPHER_API_KEY }}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "type": "twitter",
              "arguments": {
                "type": "searchbyquery",
                "query": "AI",
                "max_results": 10
              }
            }'
